# Generated by Django 5.2.1 on 2025-05-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('R', 'Receita'), ('D', 'Despesas')], max_length=1),
        ),
    ]
